title: "Latheesh Kumar E"
email: Latheesh720@live.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://cloudpro.github.io" 
twitter_username: latheesh.e
github_username:  Latheesh

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
